package com.tb.gconnect.dto.request;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;
import java.sql.Timestamp;

/**
 * @author abdul.rehman4 12th/07/2019
 * @version 1.0
 * @since v1.0
 * {@link PaymentRequest} represents the request data received at the POS/PUT requests for Payment requests
 * Rest of the documentation is covered by swager
 */
@ApiModel(value = "Payment Request Body", description = "The POSTS data required to process the payment request")
public class PaymentRequest {
    @Size(min=1, message = "acquirerId = acquirerId is invalid")
    @ApiModelProperty(name = "acquirerId", value = "acquirerId represents the merchant which can be Uber, foodpanda etc, its always greater than 0",required = true)
    private String acquirerId;

    @Size(min=1, message = "pspId = pspId is invalid")
    @ApiModelProperty(name = "pspId", value = "pspId represents GConnect PSPwhich is EasyPaisa App, its always greater than 0",required = true)
    private String pspId;

    @Size(min=1, message = "pspId = pspId is invalid")
    @ApiModelProperty(name = "pspId", value = "The unqiue identifier generated by paymentInitiator for a payment , its always greater than 0",required = true)
    private String  paymentRequestId;

    public String getAcquirerId() {
        return acquirerId;
    }

    public void setAcquirerId(String acquirerId) {
        this.acquirerId = acquirerId;
    }

    public String getPspId() {
        return pspId;
    }

    public void setPspId(String pspId) {
        this.pspId = pspId;
    }

    public String getPaymentRequestId() {
        return paymentRequestId;
    }

    public void setPaymentRequestId(String paymentRequestId) {
        this.paymentRequestId = paymentRequestId;
    }
}
